# Generated by Django 5.1.7 on 2025-03-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='facebook_account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='github_account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_known_device',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linkedin_account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter_account',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
