# Generated by Django 5.1.7 on 2025-03-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_profile_url_remove_user_facebook_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
