# Generated by Django 5.1.6 on 2025-03-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_loan_loanrepaymentschedule_payment_product_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='photo',
            field=models.ImageField(blank=1, null=1, upload_to=''),
            preserve_default=1,
        ),
    ]
