# Generated by Django 5.2.1 on 2025-05-22 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_supplier_user_alter_vendor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='user',
        ),
    ]
