# Generated by Django 4.2.13 on 2024-07-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='feed_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
