# Generated by Django 4.2.13 on 2024-07-04 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_photo_feed_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='feed_id',
        ),
    ]
